"""A2A communication layer for the Zynd network.

Mirrors the TypeScript SDK's `src/a2a/` module byte-for-byte where it
matters (canonicalization, signing). Public re-exports below.
"""

from zyndai_agent.a2a.canonical import canonical_json, canonical_bytes
from zyndai_agent.a2a.types import (
    # Wire types
    Message,
    Part,
    TextPart,
    FilePart,
    DataPart,
    FileWithBytes,
    FileWithUri,
    Task as ATask,
    Artifact,
    TaskStatus,
    TaskStatusUpdateEvent,
    TaskArtifactUpdateEvent,
    PushNotificationConfig,
    TaskPushNotificationConfig,
    ZyndAuth,
    DerivationProof,
    JsonRpcRequest,
    # Constants
    TERMINAL_STATES,
    INTERRUPTED_STATES,
    ZYND_AUTH_KEY,
    ZYND_AUTH_VERSION,
    ZYND_AUTH_DOMAIN_TAG,
    # Error codes
    RPC_PARSE_ERROR,
    RPC_INVALID_REQUEST,
    RPC_METHOD_NOT_FOUND,
    RPC_INVALID_PARAMS,
    RPC_INTERNAL_ERROR,
    A2A_TASK_NOT_FOUND,
    A2A_TASK_NOT_CANCELABLE,
    ZYND_AUTH_FAILED,
    ZYND_REPLAY_DETECTED,
    ZYND_AUTH_EXPIRED,
)
from zyndai_agent.a2a.auth import (
    sign_message,
    verify_message,
    ZyndAuthError,
    ReplayCache,
    AuthMode,
)
from zyndai_agent.a2a.adapter import (
    from_a2a_message,
    to_a2a_message,
    coerce_handler_output,
    task_reply_text,
    parts_to_reply_text,
    Attachment,
    InboundMessage,
)
from zyndai_agent.a2a.task_store import TaskStore
from zyndai_agent.a2a.server import A2AServer
from zyndai_agent.a2a.client import A2AClient, A2AError, resolve_a2a_endpoint
from zyndai_agent.a2a.card import (
    build_agent_card,
    sign_agent_card,
    AgentCardSkill,
    AgentCardProvider,
    AgentCardCapabilities,
)

__all__ = [
    "canonical_json",
    "canonical_bytes",
    "Message",
    "Part",
    "TextPart",
    "FilePart",
    "DataPart",
    "FileWithBytes",
    "FileWithUri",
    "ATask",
    "Artifact",
    "TaskStatus",
    "TaskStatusUpdateEvent",
    "TaskArtifactUpdateEvent",
    "PushNotificationConfig",
    "TaskPushNotificationConfig",
    "ZyndAuth",
    "DerivationProof",
    "JsonRpcRequest",
    "TERMINAL_STATES",
    "INTERRUPTED_STATES",
    "ZYND_AUTH_KEY",
    "ZYND_AUTH_VERSION",
    "ZYND_AUTH_DOMAIN_TAG",
    "RPC_PARSE_ERROR",
    "RPC_INVALID_REQUEST",
    "RPC_METHOD_NOT_FOUND",
    "RPC_INVALID_PARAMS",
    "RPC_INTERNAL_ERROR",
    "A2A_TASK_NOT_FOUND",
    "A2A_TASK_NOT_CANCELABLE",
    "ZYND_AUTH_FAILED",
    "ZYND_REPLAY_DETECTED",
    "ZYND_AUTH_EXPIRED",
    "sign_message",
    "verify_message",
    "ZyndAuthError",
    "ReplayCache",
    "AuthMode",
    "from_a2a_message",
    "to_a2a_message",
    "coerce_handler_output",
    "task_reply_text",
    "parts_to_reply_text",
    "Attachment",
    "InboundMessage",
    "TaskStore",
    "A2AServer",
    "A2AClient",
    "A2AError",
    "resolve_a2a_endpoint",
    "build_agent_card",
    "sign_agent_card",
    "AgentCardSkill",
    "AgentCardProvider",
    "AgentCardCapabilities",
]
